%MACRO CUSTOMERS;

DATA CLIENTS; 
	SET EXTRACT.CLNTPF(	KEEP = clntnum clttype secuityno cltsex xcltaddr01 xcltaddr02 xcltaddr03 xcltaddr04 xcltaddr05 cltpcode
							   cltphone01 cltphone02 statcode cltdob marryd xsalutl natlty ctrycode xlgivname xlsurname
						WHERE = (clntnum ne ''));
		FORMAT D_birth date9. first_name $60. last_name $60. address client $150. ID $24. POSTALCODE $10. AGE 3. GENDER $7. address2 $20.;

		IF 1900<=int(cltdob/10000)<=2100 THEN D_birth=convert_date(cltdob);
			ELSE D_birth=&errdate;
		
		AGE = year(today())-year(D_birth);
		IF AGE < 0 then AGE = 0;

		first_name = upcase(strip(compbl(xlgivname)));
		last_name = upcase(strip(compbl(xlsurname))); 

		CLIENT = CATX(' ', of xsalutl first_name last_name); 
		
		ADDRESS = CATX(' ', of xcltaddr01 xcltaddr02 xcltaddr03 xcltaddr04 xcltaddr05); 

		POSTALCODE=compress(CLTPCODE);
		postcode_pat=prxparse('/[0-9]{5}/');

		IF prxmatch(postcode_pat, postalcode)=0 or length(postalcode) ne 5 THEN POSTALCODE="NA";

		ID=upcase(compress(compress(SECUITYNO,".( ) - _", "sp")));
		IF length(ID)<=6 then ID="NA";
	
		IF INDEX(ADDRESS,'กระบี่')<>0 OR INDEX(ADDRESS,'KRABI') <> 0 THEN ADDRESS2 = 'KRABI';
		ELSE IF INDEX(ADDRESS,'กรุงเทพ')<>0     OR INDEX(ADDRESS,'BANGKOK') <> 0       OR INDEX(ADDRESS,'กทม') <> 0 OR INDEX(ADDRESS,'BANGKOK') <> 0 OR INDEX(ADDRESS,'กท') <> 0  THEN ADDRESS2 = 'BANGKOK';
		ELSE IF INDEX(ADDRESS,'กาญจนบุรี')<>0    OR INDEX(ADDRESS,'KANCHANABURI') <> 0   THEN ADDRESS2 = 'KANCHANABURI';
		ELSE IF INDEX(ADDRESS,'กาฬสินธุ์')<>0     OR INDEX(ADDRESS,'KALASIN') <> 0        THEN ADDRESS2 = 'KALASIN';
		ELSE IF INDEX(ADDRESS,'กำแพงเพชร')<>0   OR INDEX(ADDRESS,'KAMPHAENG PHET') <> 0 THEN ADDRESS2 = 'KAMPHAENG PHET';
		ELSE IF INDEX(ADDRESS,'ขอนแก่น')<>0     OR INDEX(ADDRESS,'KHON KAEN') <> 0   OR INDEX(ADDRESS,'KHON KEAN') <> 0  OR INDEX(ADDRESS,'KHONKAEN') <> 0       THEN ADDRESS2 = 'KHON KAEN';
		ELSE IF INDEX(ADDRESS,'จันทบุรี')<>0     OR INDEX(ADDRESS,'CHANTHABURI') <> 0 THEN ADDRESS2 = 'CHANTHABURI';
		ELSE IF INDEX(ADDRESS,'ฉะเชิงเทรา')<>0 OR INDEX(ADDRESS,'CHACHOENGSAO') <> 0 THEN ADDRESS2 = 'CHACHOENGSAO';
		ELSE IF INDEX(ADDRESS,'ชลบุรี')<>0 OR INDEX(ADDRESS,'CHOLBURI') <> 0 OR INDEX(ADDRESS,'CHON') <> 0 THEN ADDRESS2 = 'CHOLBURI';
		ELSE IF INDEX(ADDRESS,'ชัยนาท')<>0 OR INDEX(ADDRESS,'CHAI NAT') <> 0 THEN ADDRESS2 = 'CHAI NAT';
		ELSE IF INDEX(ADDRESS,'ชัยภูมิ')<>0 OR INDEX(ADDRESS,'CHAIYAPHUM') <> 0 THEN ADDRESS2 = 'CHAIYAPHUM';
		ELSE IF INDEX(ADDRESS,'ชุมพร')<>0 OR INDEX(ADDRESS,'CHUMPHON') <> 0 THEN ADDRESS2 = 'CHUMPHON';
		ELSE IF INDEX(ADDRESS,'เชียงราย')<>0 OR INDEX(ADDRESS,'CHIANG RAI') <> 0 OR INDEX(ADDRESS,'CHIANGRAI') <> 0 OR INDEX(ADDRESS,'CHAINGRAI') <> 0 THEN ADDRESS2 = 'CHIANG RAI';
		ELSE IF INDEX(ADDRESS,'เชียงใหม่')<>0 OR INDEX(ADDRESS,'CHIANG MAI') <> 0 OR INDEX(ADDRESS,'CHIANGMAI') <> 0 OR INDEX(ADDRESS,'CHAINGMAI') <> 0 THEN ADDRESS2 = 'CHIANG MAI';
		ELSE IF INDEX(ADDRESS,'ตรัง')<>0 OR INDEX(ADDRESS,'TRANG') <> 0 THEN ADDRESS2 = 'TRANG';
		ELSE IF INDEX(ADDRESS,'ตราด')<>0 OR INDEX(ADDRESS,'TRAT') <> 0 THEN ADDRESS2 = 'TRAT';
		ELSE IF INDEX(ADDRESS,'ตาก')<>0 OR INDEX(ADDRESS,'TAK') <> 0 THEN ADDRESS2 = 'TAK';
		ELSE IF INDEX(ADDRESS,'นครนายก')<>0 OR INDEX(ADDRESS,'NAKHON NAYOK') <> 0 THEN ADDRESS2 = 'NAKHON NAYOK';
		ELSE IF INDEX(ADDRESS,'นครปฐม')<>0 OR INDEX(ADDRESS,'PATHOM') <> 0 OR INDEX(ADDRESS,'PRATHOM') <> 0 THEN ADDRESS2 = 'NAKHON PATHOM';
		ELSE IF INDEX(ADDRESS,'นครพนม')<>0 OR INDEX(ADDRESS,'NAKHON PHANOM') <> 0 THEN ADDRESS2 = 'NAKHON PHANOM';
		ELSE IF INDEX(ADDRESS,'นครราชสีมา')<>0 OR INDEX(ADDRESS,'NAKHON RATCHASIMA') <> 0 THEN ADDRESS2 = 'NAKHON RATCHASIMA';
		ELSE IF INDEX(ADDRESS,'นครศรีธรรมราช')<>0 OR INDEX(ADDRESS,'NAKHON SI THAMMARAT') <> 0 THEN ADDRESS2 = 'NAKHON SI THAMMARAT';
		ELSE IF INDEX(ADDRESS,'นครสวรรค์')<>0 OR INDEX(ADDRESS,'SAWAN') <> 0 THEN ADDRESS2 = 'NAKHON SAWAN';
		ELSE IF INDEX(ADDRESS,'นนทบุรี')<>0 OR INDEX(ADDRESS,'NONTHABURI') <> 0 OR INDEX(ADDRESS,'NONTABURI') <> 0 THEN ADDRESS2 = 'NONTHABURI';
		ELSE IF INDEX(ADDRESS,'นราธิวาส')<>0 OR INDEX(ADDRESS,'NARATHIWAT') <> 0 THEN ADDRESS2 = 'NARATHIWAT';
		ELSE IF INDEX(ADDRESS,'น่าน')<>0 OR INDEX(ADDRESS,'NAN') <> 0 THEN ADDRESS2 = 'NAN';
		ELSE IF INDEX(ADDRESS,'บึงกาฬ')<>0 OR INDEX(ADDRESS,'BUNGKAN') <> 0 THEN ADDRESS2 = 'BUNGKAN';
		ELSE IF INDEX(ADDRESS,'บุรีรัมย์')<>0 OR INDEX(ADDRESS,'BURI RAM') <> 0 OR INDEX(ADDRESS,'BURIRAM') <> 0 THEN ADDRESS2 = 'BURI RAM';
		ELSE IF INDEX(ADDRESS,'ปทุมธานี')<>0 OR INDEX(ADDRESS,'PATHUM') <> 0 OR INDEX(ADDRESS,'PHATUM') <> 0 THEN ADDRESS2 = 'PATHUMTHANI';
		ELSE IF INDEX(ADDRESS,'ประจวบคีรีขันธ์')<>0 OR INDEX(ADDRESS,'PRACHUAP') <> 0 OR INDEX(ADDRESS,'HUA HIN') <> 0 THEN ADDRESS2 = 'PRACHUAP KHIRI KHAN';
		ELSE IF INDEX(ADDRESS,'ปราจีนบุรี')<>0 OR INDEX(ADDRESS,'PRACHIN') <> 0 THEN ADDRESS2 = 'PRACHIN BURI';
		ELSE IF INDEX(ADDRESS,'ปัตตานี')<>0 OR INDEX(ADDRESS,'PATTANI') <> 0 THEN ADDRESS2 = 'PATTANI';
		ELSE IF INDEX(ADDRESS,'พระนครศรีอยุธยา')<>0 OR INDEX(ADDRESS,'AYUTTHAYA') <> 0 THEN ADDRESS2 = 'PHRA NAKHON SRI AYUTTHAYA';
		ELSE IF INDEX(ADDRESS,'พะเยา')<>0 OR INDEX(ADDRESS,'PHAYAO') <> 0 THEN ADDRESS2 = 'PHAYAO';
		ELSE IF INDEX(ADDRESS,'พังงา')<>0 OR INDEX(ADDRESS,'PHANGNGA') <> 0 THEN ADDRESS2 = 'PHANGNGA';
		ELSE IF INDEX(ADDRESS,'พัทลุง')<>0 OR INDEX(ADDRESS,'PHATTHALUNG') <> 0 THEN ADDRESS2 = 'PHATTHALUNG';
		ELSE IF INDEX(ADDRESS,'พิจิตร')<>0 OR INDEX(ADDRESS,'PHICHIT') <> 0 THEN ADDRESS2 = 'PHICHIT';
		ELSE IF INDEX(ADDRESS,'พิษณุโลก')<>0 OR INDEX(ADDRESS,'PHITSANULOK') <> 0 THEN ADDRESS2 = 'PHITSANULOK';
		ELSE IF INDEX(ADDRESS,'เพชรบุรี')<>0 OR INDEX(ADDRESS,'PETCHABURI') <> 0 THEN ADDRESS2 = 'PETCHABURI';
		ELSE IF INDEX(ADDRESS,'เพชรบูรณ์')<>0 OR INDEX(ADDRESS,'PHETCHABUN') <> 0 THEN ADDRESS2 = 'PHETCHABUN';
		ELSE IF INDEX(ADDRESS,'แพร่')<>0 OR INDEX(ADDRESS,'PHRAE') <> 0 THEN ADDRESS2 = 'PHRAE';
		ELSE IF INDEX(ADDRESS,'ภูเก็ต')<>0 OR INDEX(ADDRESS,'PHUKET') <> 0 OR INDEX(ADDRESS,'PHU KET') <> 0 THEN ADDRESS2 = 'PHUKET';
		ELSE IF INDEX(ADDRESS,'มหาสารคาม')<>0 OR INDEX(ADDRESS,'SARAKHAM') <> 0 THEN ADDRESS2 = 'MAHA SARAKHAM';
		ELSE IF INDEX(ADDRESS,'มุกดาหาร')<>0 OR INDEX(ADDRESS,'MUKDAHAN') <> 0 THEN ADDRESS2 = 'MUKDAHAN';
		ELSE IF INDEX(ADDRESS,'แม่ฮ่องสอน')<>0 OR INDEX(ADDRESS,'MAE HONG SON') <> 0 THEN ADDRESS2 = 'MAE HONG SON';
		ELSE IF INDEX(ADDRESS,'ยโสธร')<>0 OR INDEX(ADDRESS,'YASOTHON') <> 0 THEN ADDRESS2 = 'YASOTHON';
		ELSE IF INDEX(ADDRESS,'ยะลา')<>0 OR INDEX(ADDRESS,'YALA') <> 0 THEN ADDRESS2 = 'YALA';
		ELSE IF INDEX(ADDRESS,'ร้อยเอ็ด')<>0 OR INDEX(ADDRESS,'ROI ET') <> 0 THEN ADDRESS2 = 'ROI ET';
		ELSE IF INDEX(ADDRESS,'ระนอง')<>0 OR INDEX(ADDRESS,'RANONG') <> 0 THEN ADDRESS2 = 'RANONG';
		ELSE IF INDEX(ADDRESS,'ระยอง')<>0 OR INDEX(ADDRESS,'RAYONG') <> 0 THEN ADDRESS2 = 'RAYONG';
		ELSE IF INDEX(ADDRESS,'ราชบุรี')<>0 OR INDEX(ADDRESS,'RATCHABURI') <> 0 OR INDEX(ADDRESS,'RACHA') <> 0 THEN ADDRESS2 = 'RATCHABURI';
		ELSE IF INDEX(ADDRESS,'ลพบุรี')<>0 OR INDEX(ADDRESS,'LOP BURI') <> 0 OR INDEX(ADDRESS,'LOPBURI') <> 0 THEN ADDRESS2 = 'LOP BURI';
		ELSE IF INDEX(ADDRESS,'ลำปาง')<>0 OR INDEX(ADDRESS,'LAMPANG') <> 0 THEN ADDRESS2 = 'LAMPANG';
		ELSE IF INDEX(ADDRESS,'ลำพูน')<>0 OR INDEX(ADDRESS,'LAMPHUN') <> 0 THEN ADDRESS2 = 'LAMPHUN';
		ELSE IF INDEX(ADDRESS,'เลย')<>0 OR INDEX(ADDRESS,'LOEI') <> 0 THEN ADDRESS2 = 'LOEI';
		ELSE IF INDEX(ADDRESS,'ศรีสะเกษ')<>0 OR INDEX(ADDRESS,'SI SA KET') <> 0 OR INDEX(ADDRESS,'SISAKET') <> 0 THEN ADDRESS2 = 'SI SA KET';
		ELSE IF INDEX(ADDRESS,'สกลนคร')<>0 OR INDEX(ADDRESS,'SAKON') <> 0 THEN ADDRESS2 = 'SAKON NAKHON';
		ELSE IF INDEX(ADDRESS,'สงขลา')<>0 OR INDEX(ADDRESS,'SONGKHLA') <> 0 OR INDEX(ADDRESS,'SONGKHA') <> 0  OR INDEX(ADDRESS,'HATYAI') <> 0 THEN ADDRESS2 = 'SONGKHLA';
		ELSE IF INDEX(ADDRESS,'สตูล')<>0 OR INDEX(ADDRESS,'SATUN') <> 0 THEN ADDRESS2 = 'SATUN';
		ELSE IF INDEX(ADDRESS,'สมุทรปราการ')<>0 OR INDEX(ADDRESS,'PRAKAN') <> 0 OR INDEX(ADDRESS,'PRAKARN') <> 0 THEN ADDRESS2 = 'SAMUT PRAKAN';
		ELSE IF INDEX(ADDRESS,'สมุทรสงคราม')<>0 OR INDEX(ADDRESS,'SAMUT SONGKHRAM') <> 0  OR INDEX(ADDRESS,'SONGKHRAM') <> 0 THEN ADDRESS2 = 'SAMUT SONGKHRAM';
		ELSE IF INDEX(ADDRESS,'สมุทรสาคร')<>0 OR INDEX(ADDRESS,'SAKHON') <> 0 OR INDEX(ADDRESS,'SAKHON') <> 0 THEN ADDRESS2 = 'SAMUT SAKHON';
		ELSE IF INDEX(ADDRESS,'สระแก้ว')<>0 OR INDEX(ADDRESS,'SA KAEO') <> 0 THEN ADDRESS2 = 'SA KAEO';
		ELSE IF INDEX(ADDRESS,'สระบุรี')<>0 OR INDEX(ADDRESS,'SARABURI') <> 0 THEN ADDRESS2 = 'SARABURI';
		ELSE IF INDEX(ADDRESS,'สิงห์บุรี')<>0 OR INDEX(ADDRESS,'SING BURI') <> 0 THEN ADDRESS2 = 'SING BURI';
		ELSE IF INDEX(ADDRESS,'สุโขทัย')<>0 OR INDEX(ADDRESS,'SUKHOTHAI') <> 0 THEN ADDRESS2 = 'SUKHOTHAI';
		ELSE IF INDEX(ADDRESS,'สุพรรณบุรี')<>0 OR INDEX(ADDRESS,'SUPHAN BURI') <> 0 THEN ADDRESS2 = 'SUPHAN BURI';
		ELSE IF INDEX(ADDRESS,'สุราษฎร์ธานี')<>0 OR INDEX(ADDRESS,'SURAT') <> 0 THEN ADDRESS2 = 'SURAT THANI';
		ELSE IF INDEX(ADDRESS,'สุรินทร์')<>0 OR INDEX(ADDRESS,'SURIN') <> 0 THEN ADDRESS2 = 'SURIN';
		ELSE IF INDEX(ADDRESS,'หนองคาย')<>0 OR INDEX(ADDRESS,'NONG KHAI') <> 0 THEN ADDRESS2 = 'NONG KHAI';
		ELSE IF INDEX(ADDRESS,'หนองบัวลำภู')<>0 OR INDEX(ADDRESS,'NONG BUA LAM PHU') <> 0 THEN ADDRESS2 = 'NONG BUA LAM PHU';
		ELSE IF INDEX(ADDRESS,'อ่างทอง')<>0 OR INDEX(ADDRESS,'ANG THONG') <> 0 THEN ADDRESS2 = 'ANG THONG';
		ELSE IF INDEX(ADDRESS,'อำนาจเจริญ')<>0 OR INDEX(ADDRESS,'AMNAT CHAROEN') <> 0 THEN ADDRESS2 = 'AMNAT CHAROEN';
		ELSE IF INDEX(ADDRESS,'อุดรธานี')<>0 OR INDEX(ADDRESS,'UDON') <> 0 OR INDEX(ADDRESS,'UDORN') <> 0 THEN ADDRESS2 = 'UDON THANI';
		ELSE IF INDEX(ADDRESS,'อุตรดิตถ์')<>0 OR INDEX(ADDRESS,'UTTARADIT') <> 0 THEN ADDRESS2 = 'UTTARADIT';
		ELSE IF INDEX(ADDRESS,'อุทัยธานี')<>0 OR INDEX(ADDRESS,'UTHAI THANI') <> 0 THEN ADDRESS2 = 'UTHAI THANI';
		ELSE IF INDEX(ADDRESS,'อุบลราชธานี')<>0 OR INDEX(ADDRESS,'UBON RATCHATHANI') <> 0 THEN ADDRESS2 = 'UBON RATCHATHANI';
		ELSE IF INDEX(ADDRESS,'PARIS') <> 0 OR INDEX(ADDRESS,'FRANCE') <> 0 THEN ADDRESS2 = 'FRANCE';
		ELSE IF INDEX(ADDRESS,'HONG KONG') <> 0 OR INDEX(ADDRESS,'HONGKONG') <> 0 THEN ADDRESS2 = 'HONG KONG';
		ELSE IF INDEX(ADDRESS,'GERMANY') <> 0 THEN ADDRESS2 = 'GERMANY';
		ELSE IF INDEX(ADDRESS,'AUSTRALIA') <> 0 THEN ADDRESS2 = 'AUSTRALIA';
		ELSE IF INDEX(ADDRESS,'INDIA') <> 0 THEN ADDRESS2 = 'INDIA';
		ELSE IF INDEX(ADDRESS,'CANADA') <> 0 THEN ADDRESS2 = 'CANADA';
		ELSE IF INDEX(ADDRESS,'SINGAPORE') <> 0 THEN ADDRESS2 = 'SINGAPORE';
		ELSE IF INDEX(ADDRESS,'U.S.A.') <> 0 THEN ADDRESS2 = 'U.S.A.';
		ELSE IF INDEX(ADDRESS,'SWITZERLAND') <> 0 THEN ADDRESS2 = 'SWITZERLAND';
		ELSE IF INDEX(ADDRESS,'JAPAN') <> 0 THEN ADDRESS2 = 'JAPAN';
		ELSE IF INDEX(ADDRESS,'UNITED KINGDOM') <> 0 OR INDEX(ADDRESS,'U.K.') <> 0 THEN ADDRESS2 = 'U.K.';
		ELSE IF INDEX(ADDRESS,'NEW ZEALAND') <> 0 THEN ADDRESS2 = 'NEW ZEALAND';
		ELSE IF INDEX(ADDRESS,'NETHERLAND') <> 0 THEN ADDRESS2 = 'NETHERLAND';
		ELSE IF INDEX(ADDRESS,'SPAIN') <> 0 THEN ADDRESS2 = 'SPAIN';
		ELSE IF INDEX(ADDRESS,'ITALY') <> 0 THEN ADDRESS2 = 'ITALY';
		ELSE IF INDEX(ADDRESS,'PORTUGAL') <> 0 THEN ADDRESS2 = 'PORTUGAL';
		ELSE IF INDEX(ADDRESS,'NORWAY') <> 0 THEN ADDRESS2 = 'NORWAY';
		ELSE IF INDEX(ADDRESS,'BELGIUM') <> 0 THEN ADDRESS2 = 'BELGIUM';
		ELSE IF INDEX(ADDRESS,'SWEDEN') <> 0 THEN ADDRESS2 = 'SWEDEN';
		ELSE ADDRESS2 = 'NA';

		IF 	cltsex = 'M' THEN gender = 'MALE';
		ELSE IF cltsex = 'F' THEN gender = 'FEMALE';
		ELSE gender = 'UNKNOWN';
	
	RENAME	marryd = marital_status
			natlty = nationality
			clttype = client_type
			ctrycode = country
			ADDRESS2 = ADDRESS_GROUP;

	LABEL	marryd = 'marital_status'
			natlty = 'nationality'
			clttype = 'client_type'
			ctrycode = 'country'
			ADDRESS2 = "ADDRESS_GROUP";

	cltsex = COALESCEC(cltsex , 	"N");
	cltphone01 = COALESCEC(cltphone01 , 	"NA");
	cltphone02 = COALESCEC(cltphone02 , 	"NA");
	statcode = COALESCEC(statcode , 	"NA");
	ADDRESS_GROUP = COALESCEC(ADDRESS_GROUP , 	"NA");

	DROP xsalutl xlsurname xlgivname xsalutl xcltaddr01 xcltaddr02 xcltaddr03 xcltaddr04 xcltaddr05 cltpcode secuityno cltdob postcode_pat;
RUN;

PROC SORT NODUPKEYS;
	BY clntnum;
RUN;

DATA CLIENTSEXTRA;
	SET EXTRACT.clexpf ( KEEP = clntnum rmblphone rinternet);
	FORMAT rinternet $50. rmblphone $16.;

	IF INDEX(rinternet,'@')eq 0 THEN rinternet = 'NA';
	rmblphone = COMPRESS(rmblphone,".( ) - _ @ + F M D M","s");
	IF rmblphone eq ' ' or . THEN rmblphone ='NA';

	RENAME	rmblphone = mobile
			rinternet = email;
	LABEL	rmblphone = 'mobile'
			rinternet = 'email';
	
RUN;

PROC SORT NODUPKEYS;
	BY clntnum;
RUN;

DATA TRANSV.CLIENTS;
	MERGE 	CLIENTS( In = a)
			CLIENTSEXTRA;
	BY clntnum;
	IF a;

	email = COALESCEC(trim(email) , "NA");
	mobile = COALESCEC(trim(mobile) , "NA");
	address = COALESCEC(trim(address) , "NA");
RUN;

%MEND;
